Splash screen Added
smaranjitghose/Upcharika pull request #14
Opened 2021-06-15 05:51 UTC by karanpatel2329

#5 issue is fixed.
I have added a splash screen using flutter package -- flutter_native_splash.

2021-06-15 15:49 UTC, smaranjitghose commented
> #5 issue is fixed.
> I have added a splash screen using flutter package -- flutter_native_splash.

Please follow the guidelines given on slack. You are requested to provide a clip/snapshot of the changes for all the PRs

2021-06-16 03:49 UTC, karanpatel2329 commented
> > #5 issue is fixed.
> > I have added a splash screen using flutter package -- flutter_native_splash.
> 
> Please follow the guidelines given on slack. You are requested to provide a clip/snapshot of the changes for all the PRs

![splash screen](https://user-images.githubusercontent.com/51056125/122155095-e3093080-ce83-11eb-8120-09634c7e3df1.jpeg)
![homepage](https://user-images.githubusercontent.com/51056125/122155099-e4d2f400-ce83-11eb-966a-74cc38661bda.jpeg)

2021-06-16 07:27 UTC, anushbhatia requested changes
https://www.flaticon.com/free-icon/nurse_1788280?term=nurse&related_id=1788280
You can use this logo and avoid using capital letters in the splash screen.

2021-06-16 07:30 UTC, anushbhatia commented on web/splash/style.css
> +      margin:0;
What is the use of modfying this we aren't using flutter web for this project

2021-06-16 07:31 UTC, anushbhatia commented on pubspec.yaml
> +  flutter_native_splash:
Mention this above the dev_dependencies

2021-06-16 07:32 UTC, anushbhatia reviewed
Also, don't push .idea named files to add them in gitignore so that they won't be pushed

2021-06-16 20:10 UTC, smaranjitghose commented
> > > #5 issue is fixed.
> > > I have added a splash screen using flutter package -- flutter_native_splash.
> > 
> > 
> > Please follow the guidelines given on slack. You are requested to provide a clip/snapshot of the changes for all the PRs
> 
> ![splash screen](https://user-images.githubusercontent.com/51056125/122155095-e3093080-ce83-11eb-8120-09634c7e3df1.jpeg)
> ![homepage](https://user-images.githubusercontent.com/51056125/122155099-e4d2f400-ce83-11eb-966a-74cc38661bda.jpeg)

Could you upload a clip of the splash screen please from the emulator? If it's just a static image, that's not good enough

2021-06-24 16:24 UTC, anushbhatia commented
Any update you can create a new pr with changes it will work now cause all other files are commented.

2021-06-24 16:24 UTC, closed without merging