Added a simple onboarding screen.
smaranjitghose/Upcharika pull request #23
Opened 2021-06-23 09:19 UTC by adityathakurxd

PR for Adding an Onboarding screen #6

I have used the `flutter_card_swipper: ^0.4.0` to create a swiping onboarding screen.
Also, set it as home in `main.dart` so it opens up first when user starts the app.

Let me know if any changes are required to the description.

### Video 

https://user-images.githubusercontent.com/53579386/123071211-16266380-d432-11eb-86bc-ff206ea0e788.mp4

2021-06-23 16:25 UTC, smaranjitghose approved these changes

2021-06-23 16:25 UTC, smaranjitghose commented on .flutter-plugins
> +wakelock=C:\\Users\\Asus\\AppData\\Roaming\\Pub\\Cache\\hosted\\pub.dartlang.org\\wakelock-0.1.4+2\\
@anushbhatia  I believe we can gitignore this file?

2021-06-23 16:25 UTC, smaranjitghose commented on .flutter-plugins-dependencies
> +{"info":"This is a generated file; do not edit or check into version control.","plugins":{"ios":[{"name":"camera","path":"C:\\\\Users\\\\Asus\\\\AppData\\\\Roaming\\\\Pub\\\\Cache\\\\hosted\\\\pub.da
@anushbhatia  I believe we can gitignore this file?

2021-06-24 08:45 UTC, anushbhatia requested changes
@adityathakurxd yes add these .plugins .dependeicies in git ignore

2021-06-24 09:12 UTC, adityathakurxd commented
@anushbhatia I have added these files to gitignore

2021-06-24 10:23 UTC, adityathakurxd commented
I deleted the .flutter-plugins and .flutter-plugins-dependencies so they wouldn't merge on main.

2021-06-24 13:09 UTC, smaranjitghose approved these changes

2021-06-24 15:31 UTC, anushbhatia approved these changes

2021-06-24 15:39 UTC, merged